pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        maven {
            url 'https://maven-dev.tcmppcloud.com/fHKFBbEjd/repository/maven-public/'
        }
        maven {
            url 'https://tcmpp-work-maven.pkg.coding.net/repository/tcmpp/android'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
//    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://maven-dev.tcmppcloud.com/fHKFBbEjd/repository/maven-public/'
        }
        maven {
            url 'https://tcmpp-work-maven.pkg.coding.net/repository/tcmpp/android'
        }
    }


}

rootProject.name = "MiniApp Tester"
include ':app'
